### ISSUE TITLE
Link Attributes support?

### ISSUE THREAD

**Issue by jameswilson** [Ymbra/migrate_default_content#62]
Trying to import some default classes (via [link_attributes](https://www.drupal.org/project/link_attributes) module) with my default menu_link_content.   

On the edit form the field name is `link[0][options][attributes][class]`.

Link Attributes integration with Drupal core menus leverages the `menu_link_content_data` database table's `link__options` column and the data is serialized.

<img width="1440" alt="screenshot 2018-03-12 10 02 05" src="https://user-images.githubusercontent.com/243532/37291458-ae7c0b06-25dc-11e8-8b4b-f5e4efe6be33.png">

I've tried importing this value in a  couple formats (see below) and neither work.

<img width="556" alt="screenshot 2018-03-11 12 12 40" src="https://user-images.githubusercontent.com/243532/37256211-7e620572-2525-11e8-889d-1285e9b80363.png">

Attempt 1:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  class: icon-twitter
  weight: -10
```

Attempt 2:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  optionsAttributesClass: icon-twitter
  weight: -10
```

Attempt 3:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  options:
    attributes:
      class: icon-twitter
  weight: -10
```

Attempt 4:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  linkOptionsAttributesClass: icon-twitter
  weight: -10
```

Attempt 5:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  link:
    options:
       attributes:
         class: icon-twitter
  weight: -10
```

Attempt 6:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  options: 'a:1:{s:10:"attributes";a:1:{s:5:"class";s:12:"icon-twitter";}}'
  weight: -10
```

Attempt 7:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  linkUri: https://twitter.com/myhandle
  linkOptions: 'a:1:{s:10:"attributes";a:1:{s:5:"class";s:12:"icon-twitter";}}'
  weight: -10
```

Attempt 8:
```
-
  title: Twitter
  menu_name: social-links
  uid: 1
  link:
    uri: https://twitter.com/myhandle
    options: 'a:1:{s:10:"attributes";a:1:{s:5:"class";s:12:"icon-twitter";}}'
  weight: -10
```
^ this last one actually triggered an error message but was also the *only* one of them all to result in an actual value (`N;`) ending up in the `link__options` column, however the `link__uri` field was empty.

The error was:

```
Call to a member function getUrl() on null in Drupal\menu_link_content\Entity\MenuLinkContent->getUrlObject() (line 78 of web/core/modules/menu_link_content/src/Entity/MenuLinkContent.php)
```

If I handle / prevent that error from happening in the MenuLinkContent.php getUrlObject function, it doesn't really solve the problem.

Do you have any suggestions?  Thanks.
